#! /usr/bin/env bash

# ** General Note **
# This script needs several improvements:
# * Show information while running the installation process
# * Install is done after each restart, which can be annoying and time-consuming
# * The playwright process needs proper handling - currently it is just a disgusting hack

set +x

trap "echo 'Ctrl+C pressed. Exiting...'; kill 0" SIGINT

container_port=$(ddev exec "yq '.web_extra_exposed_ports[] | select(.name == \"playwright\") | .container_port' /mnt/ddev_config/config.yaml")
https_port=$(ddev exec "yq '.web_extra_exposed_ports[] | select(.name == \"playwright\") | .https_port' /mnt/ddev_config/config.yaml")

if [ -z "$https_port" ] || [ -z "$container_port" ]; then
  echo "Please expose ports for playwright in the projects \".ddev/config.yaml -> web_extra_exposed_ports\" section"
  exit 1
fi

# First, ensure no processes/leftovers are running
if ddev exec "ps -ax | grep playwright | grep -v grep | awk '{print \$1}'" | grep -q .; then
    echo "Stop currently running playwright processes."
    # @todo: Killing processes may cause issues. Better find a way to "stop" the running process
    ddev exec "ps -ax | grep playwright | grep -v grep | awk '{print \$1}' | xargs kill -9 > /dev/null" > /dev/null
fi

function information() {
    while [ "$(ddev exec 'curl -o /dev/null -L -s -w "%{http_code}" http://0.0.0.0:43837 &2> /dev/null')" != "200" ]; do
      trap "echo 'Ctrl+C pressed. Exiting...'; exit" SIGINT
      echo "Waiting for port ${https_port:-no port defined}"
      sleep 2
    done

    echo "The playwright GUI is located under https://${DDEV_SITENAME}.ddev.site:${https_port}"
}

information & ddev exec "cd /var/www/html/ && sudo npx playwright install-deps && npx playwright install && npx playwright test --ui --ui-port=${container_port} --ui-host=0.0.0.0 > /dev/null || exit 0" > /dev/null